pipeline:
  test:
    image: alp-py36-min:latest
    environment:
      - PDNS_API_KEY=${PDNS_API_KEY}
    secrets: [ pdns_api_key ]
    commands:
      - apk add -u --no-cache --virtual .build-deps gcc python3-dev build-base linux-headers
      - python3.6 -m venv /srv/venv 
      - source /srv/venv/bin/activate
      - pip install -r requirements.txt
      - python tests.py 

  publish:
    image: plugins/docker
    repo: pdns-utils
    registry: my.docker-repo.com
    secrets: [ docker_username, docker_password ]
    custom_dns: [ 10.x.x.x, 10.8.x.x ]
    tags:
      - ${DRONE_TAG}
      - latest
    when:
      event: tag
